######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 7 14:06:49 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

RESOURCES += application.qrc
