######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 8 08:39:43 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mydialog.h
SOURCES += mydialog.cpp main.cpp
RESOURCES += application.qrc
